### PR TITLE
Send broadcast issue fixed

### LINKED ISSUE #2111: Send message to staff is not working
**Describe the bug**
When adding a node for send message to staff, it does not send message even if the staff is opted in.

**To Reproduce**
1. Go to [cc.tides.coloredcow.com](https://cc.tides.coloredcow.com/flow/configure/0381bc23-1a27-4920-b65e-136f8876a7c8)
2. Run flow for simulator
3. The HSM is not send to staff member

**Expected behavior**
The HSM should be sent to staff member

### PR DESCRIPTION
**Pull request by mdshamoon**
## Summary

- Send broadcast issue fixed https://github.com/glific/glific-frontend/issues/2111
- Code cleanup

### CODE REVIEW

File: src/components/flow/actions/sendbroadcast/SendBroadcastForm.tsx [hunk 1]
```diff
@@ -71,7 +64,7 @@ export default class SendBroadcastForm extends React.Component<
     if (this.state.template.value !== null) {
       fetchAsset(this.props.assetStore.templates, this.state.template.value.uuid).then(
         (asset: Asset) => {
-          if (asset !== null) {
+          if (asset && asset.content) {
```
Comment (pankaj-ag) [inline src/components/flow/actions/sendbroadcast/SendBroadcastForm.tsx:67]: I think you can also use like this asset?.content

**Review by pankaj-ag — APPROVED** [review]
Okay I did not see any changes in the expression. I hope you have tested it.

File: src/components/flow/actions/sendbroadcast/SendBroadcastForm.tsx (hunk 1 above)
Comment (mdshamoon) [reply src/components/flow/actions/sendbroadcast/SendBroadcastForm.tsx:67]: @pankaj-ag optional chaining is released in typescript version 3.7. Here we are using 3.4.

Will update this when floweditor updates the typescript version.

File: src/components/flow/actions/sendbroadcast/SendBroadcastForm.tsx [hunk 2]
```diff
@@ -242,7 +201,7 @@ export default class SendBroadcastForm extends React.Component<
 
       const templateVariables =
         this.state.templateVariables.length === 0 ||
-        (this.state.template.value && this.state.template.value.id !== template.id)
+        (this.state.template.value && this.state.template.value.uuid !== template.uuid)
           ? range(0, templateTranslation.variable_count).map(() => {
```
Comment (mdshamoon) [inline src/components/flow/actions/sendbroadcast/SendBroadcastForm.tsx:205]: @pankaj-ag The main issue was the check with id in these lines. Floweditor uses template ids and we use uuids.
We needed to check based on uuid of the template rather than the id to update variables that we are sending
