### PR TITLE
Fix/webhook function

### LINKED ISSUE #179: Bug: Webhook Function Dropdown Not working Properly
## **Describe the bug**

- Related PR: Add list of webhook functions as dropdown in call a webhook node (#172)
- Original Target Issue: [www.github.com/glific/glific-frontend/issues/3200](https://github.com/glific/glific-frontend/issues/3200)

- The new feature that allows selecting a function in the Call a Webhook node is working partially, but has multiple functional issues. The dropdown loads and selection works, but the UI does not update all fields correctly, leading to inconsistent behavior.

### **Expected Behavior**

- Function dropdown should load all functions correctly.

- Selecting a function should:
        - Switch the node to Function Mode
        - Disable the URL field
         - Auto-handle body/header logic
         - Correctly populate the function details
         - Clearing the selection should fully revert back to URL mode.

### **Steps to Reproduce**

1. Go to Flow Editor → Add a Call a Webhook node.
2. Open the Function dropdown.
3. Select a function.

### PR DESCRIPTION
**Pull request by priyanshu6238**
Test all point which is mention below:

Screenshot 2025-11-25 at 2 11 17 PM

### CODE REVIEW

File: src/components/flow/routers/webhook/WebhookRouterForm.tsx [hunk 1]
```diff
@@ -102,23 +102,27 @@ export default class WebhookRouterForm extends React.Component<
...
+
+      const shouldResetBody = !prevFunction || selected.name !== prevFunctionName;
+
+      updates.body = {
+        value: shouldResetBody ? backendDefaultBody : currentBody
+      };
+    } else {
+      updates.body = { value: '' };
+    }
+
```
Comment (akanshaaa19) [inline src/components/flow/routers/webhook/WebhookRouterForm.tsx:125]: instead of checking all of this here can we not move all this to the nodeToState function in helper? and keep the handleChange function simple. look at how we were handling the body earlier

File: src/components/flow/routers/webhook/WebhookRouterForm.tsx [hunk 2]
```diff
@@ -152,12 +156,18 @@ export default class WebhookRouterForm extends React.Component<
...
+          updates.webhookFunction = { value: null };
+        }
 
-        // Only set default body for non-FUNCTION methods
         if (newMethod !== Methods.FUNCTION) {
           updates.body = { value: getDefaultBody(newMethod) };
+          updates.url = { value: '' };
+        }
+        if (oldMethod === Methods.FUNCTION && newMethod !== Methods.FUNCTION) {
+          updates.url = { value: '' };
```
Comment (akanshaaa19) [inline src/components/flow/routers/webhook/WebhookRouterForm.tsx:169]: same here we should not have so many checks, on function change just update the body in one single function

**Review by akanshaaa19 — CHANGES_REQUESTED** [review]
Can we move the functions which are setting the initial state to the nodeToState function? Even the api call result should be moved there if possible and then all the things should be taken from the state. Keep the changes in `src/components/flow/routers/webhook/WebhookRouterForm.tsx` simple

**Comment by priyanshu6238** [comment]
> Can we move the functions which are setting the initial state to the nodeToState function? Even the api call result should be moved there if possible and then all the things should be taken from the state. Keep the changes in `src/components/flow/routers/webhook/WebhookRouterForm.tsx` simple

@akanshaaa19  There is a problem , we cannot move most of the logic to nodeToState, because nodeToState only runs once during the initial load. However, the initial values inside the function need to update whenever the function option is changed.

**Review by madclaws — APPROVED** [review]
Tested, working fine.

**Review by akanshaaa19 — APPROVED** [review]
